//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp5_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        protected string _pid;
        protected string _name;
        protected int _quantity;
        protected decimal _cost;
        protected decimal _sellingPrice;

        protected int pid_length = 6;
        protected int name_length = 30;


        public string ProductID { 
            get { return this._pid; } 
            set {
                if (value.Length > pid_length)
                {
                    this._pid = value.Substring(0, pid_length);
                }
                else
                    this._pid = value;
            } 
        }
        public string Name
        {
            get { return this._name; }
            set
            {
                if (value.Length > name_length)
                {
                    this._name = value.Substring(0, name_length);
                }
                else
                    this._name = value;
            }
        }
        public int Quantity
        {
            get { return this._quantity; }
            set
            {
                if (value > int.MaxValue)
                {
                    this._quantity = int.MaxValue;
                }
                else if (value == null) {
                    this._quantity = 0;
                }
                else
                    this._quantity = value;
            }
        }
        public decimal Cost
        {
            get { return this._cost; }
            set
            {
                if (value > decimal.MaxValue)
                {
                    this._cost = decimal.MaxValue;
                }
                else if(value == null){
                    this._cost = 0;
                }
                else
                    this._cost = value;
            }
        }
        public decimal SellingPrice
        {
            get { return this._sellingPrice; }
            set
            {
                if (value > decimal.MaxValue)
                {
                    this._sellingPrice = decimal.MaxValue;
                }
                else if (value == null)
                {
                    this._sellingPrice = 0;
                }
                else
                    this._sellingPrice = value;
            }
        }
    }
}
